### ISSUE TITLE
TableModel No sort function, can it be added?

### ISSUE THREAD

**Issue by wangqiangcc** [narizhny/qt-mvc-templates#3]
hello! 
 TableModel No sort function, can it be added?

**Comment by narizhny** [comment]
It possible, but I think QSortFilterProxyModel is more usefull.
If you sort the internal container using std::sort, it will be necessary to call QAbstractItemModel::beginResetModel and QAbstractItemModel::endResetModel  . That will lead to loss of the selection of the element.
And also QSortFilterProxyModel  allows users to change sort order or column via table header.
